import { type LogContext } from '@grafana/faro-web-sdk';

export type LoggerDefaults = { context?: Omit<LogContext, 'source'>; logToConsole?: boolean };

export const Loggers = {
  /* new loggers should follow package/area.feature naming convention */
  'grafana/runtime.plugins.meta': { logToConsole: true },
  'grafana/runtime.plugins.settings': { logToConsole: true },
  'grafana/runtime.plugins.datasource': { logToConsole: true },
  'grafana/runtime.utils.getCachedPromise': {},

  /* existing loggers that keep their existing source name */
  sandbox: {},
  'ui-extension-logs': {},
  'features.plugins': {},
  'features.alerting': { context: { module: 'Alerting' } },
  'features.correlations': {},
  'features.dashboards.genai': {},
  'features.query-history.local-storage': {},
  'features.query-history.indexeddb': {},
  /* public/app/features domain loggers */
  'features.actions': {},
  'features.admin': {},
  'features.annotations': {},
  'features.apiserver': {},
  'features.auth-config': {},
  'features.browse-dashboards': {},
  'features.canvas': {},
  'features.command-palette': {},
  'features.dashboard': {},
  'features.dashboard-scene': {},
  'features.datasources': {},
  'features.dimensions': {},
  'features.explore': {},
  'features.expressions': {},
  'features.geo': {},
  'features.inspector': {},
  'features.library-panels': {},
  'features.live': {},
  'features.logs': {},
  'features.loki-helpers': {},
  'features.panel': {},
  'features.panel-screenshot': {},
  'features.profile': {},
  'features.provisioning': {},
  'features.query': {},
  'features.scopes': {},
  'features.search': {},
  'features.serviceaccounts': {},
  'features.stars': {},
  'features.teams': {},
  'features.templating': {},
  'features.theme-playground': {},
  'features.transformers': {},
  'features.variables': {},
  'core.crash-detection': {},
  'core.utils.time-regions': {},
  'core.utils.short-links': {},
  'core.utils.explore': {},
  'core.utils.fetch': {},
  'core.utils.metrics': {},
  'core.trusted-types': { logToConsole: true },
  'core.journeys': { logToConsole: true },
  'core.notifications': {},
  'core.navigation': {},
  'core.services.meticulous': {},
  'core.services.context': {},
  'core.services.backend': {},
  'core.echo': {},
  'core.components.role-picker': {},
  'core.components.time-picker': {},
  'core.components.access-control': {},
  'core.components.invite-user': {},
  'core.components.login': {},
  'core.components.nav-landing-page': {},
  'core.legacy-api': {},
  'extensions.auth-config.scim': { context: { module: 'SCIM' } },

  /* top-level public/app (excluding features/plugins/core) */
  app: {},
  'app.api.provisioning': {},

  /* built-in plugins under public/app/plugins */
  'plugins/panel.canvas': {},
  'plugins/panel.geomap': {},
  'plugins/panel.heatmap': {},
  'plugins/panel.live': {},
  'plugins/panel.logs': {},
  'plugins/panel.logstable': {},
  'plugins/panel.news': {},
  'plugins/panel.timeseries': {},
  'plugins/datasource.azuremonitor': {},
  'plugins/datasource.cloudwatch': {},
  'plugins/datasource.dashboard': {},
  'plugins/datasource.grafana': {},
  'plugins/datasource.graphite': {},
} satisfies Record<string, LoggerDefaults>;

export type LoggerSource = keyof typeof Loggers;
