// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     public/app/plugins/gen.go
// Using jennies:
//     TSTypesJenny
//     PluginTsTypesJenny
//
// Run 'make gen-cue' from repository root to regenerate.

// Generated from public/app/plugins/panel/timeseries/panelcfg.cue file.

import * as common from '@grafana/schema';

export interface TimeSeriesLegendOptions extends common.VizLegendOptions {
  enableFacetedFilter?: boolean;
  facetedFilterPinned?: boolean;
}

export const defaultTimeSeriesLegendOptions: Partial<TimeSeriesLegendOptions> = {
  enableFacetedFilter: false,
  facetedFilterPinned: false,
};

/**
 * Kind of derived series drawn on top of the source series
 */
export enum TimeSeriesOverlayType {
  LinearRegression = 'linearRegression',
  MovingAverage = 'movingAverage',
}

export interface TimeSeriesOverlayOptions {
  /**
   * Draw a derived series computed from the source data
   */
  enabled: boolean;
  /**
   * Which derived series to compute
   */
  type: TimeSeriesOverlayType;
  /**
   * Number of trailing points averaged by the moving average overlay
   */
  windowSize: number;
}

export const defaultTimeSeriesOverlayOptions: Partial<TimeSeriesOverlayOptions> = {
  enabled: false,
  type: TimeSeriesOverlayType.MovingAverage,
  windowSize: 10,
};

export interface Options extends common.OptionsWithTimezones, common.OptionsWithAnnotations {
  disableKeyboardEvents?: boolean;
  legend: TimeSeriesLegendOptions;
  orientation?: common.VizOrientation;
  overlay?: TimeSeriesOverlayOptions;
  timeCompare?: common.TimeCompareOptions;
  tooltip: common.VizTooltipOptions;
}

export interface FieldConfig extends common.GraphFieldConfig {}
